/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
<<<<<<< HEAD

=======
  const IEpPlus: typeof import('~icons/ep/plus')['default']
>>>>>>> dev1
}
